# AWSTemplateFormatVersion: "2010-09-09"
# Description: A sample template
Parameters:
  MyKeyPairName:
    Type: String
  MyImageId:
    Type: String

Resources:
  MyEC2Instance: #An inline comment
    Type: "AWS::EC2::Instance"
    Properties:
      UserData:
        Fn::Base64: |
          #!/bin/bash
          cd ~/
          yum update &&  yum install -y python3-pip &&  yum install -y git
          git clone https://github.com/nasa-petal/discord_bot.git
          cd discord_bot
          cat > .env <<EOF
          OPENAI_API_KEY = xxx
          DISCORD_TOKEN = xxx
          EOF
          pip3 install -r requirements.txt
          screen -S discord
          python3 bot.py
          screen -d discord
      SecurityGroups:
        - !Ref MySecurityGroup
      ImageId: !Ref MyImageId # "ami-016e85441bf937878" #Another comment -- This is a Linux AMI
      InstanceType: t2.micro
      KeyName: !Ref MyKeyPairName # kp
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allowing SSH from everywhere
      SecurityGroupIngress:
        - IpProtocol: tcp
          ToPort: "22"
          FromPort: "22"
          CidrIp: 0.0.0.0/0
